name: Compile LaTeX and Upload to Google Drive

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar LaTeX
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended latexmk

      # 3. Compilar PDF
      - name: Compile LaTeX
        run: latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex

      # 4. Empaquetar resultados
      - name: Package PDF
        run: mkdir build && cp main.pdf build/

      # 5. Subir a Google Drive
      - name: Upload to Google Drive
        uses: satackey/action-google-drive@v1
        with:
          service_account_key: ${{ secrets.GDRIVE_CREDENTIALS }}
          upload_file: ./build/main.pdf
          drive_file: main.pdf
